# -*- coding: utf-8 -*-
"""Helper_Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zFtgkY2ocMZikcovG4-OuWsGDrfJfKyu
"""

import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import time
import tensorflow as tf
from tensorflow.keras.layers import Layer
from tensorflow.keras import initializers
from tensorflow.keras import backend as K
from __future__ import print_function

import sys
import os
import time
import tensorflow as tf
from tensorflow.keras.layers import Input, Dropout, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import MeanSquaredError, Hinge
from tensorflow.keras.metrics import Mean, SparseCategoricalAccuracy
import numpy as np
fashion_mnist = tf.keras.datasets.fashion_mnist
import pandas as pd
from tensorflow.keras.layers import Input, Dropout, Flatten
from tensorflow.keras.models import Model

import numpy as np
np.random.seed(1234)  # for reproducibility

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from sklearn.utils import shuffle

from collections import OrderedDict

# Hard sigmoid function for binary weights
def hard_sigmoid(x):
    return tf.clip_by_value((x + 1.0) / 2.0, 0, 1)

# BinaryConnect weight binarization function
def binarization(W, H, binary=True, deterministic=False, stochastic=False, seed=None):
    if not binary or (deterministic and stochastic):
        return W
    else:
        Wb = hard_sigmoid(W / H)

        if stochastic:
            # Apply random binomial sampling for stochastic BinaryConnect
            Wb = tf.dtypes.cast(
                tf.random.stateless_binomial(shape=tf.shape(W), seed=seed, counts=1, probs=Wb),
                tf.float32
            )
        else:
            # Deterministic rounding for deterministic BinaryConnect
            Wb = tf.round(Wb)
        # Mapping binary values to original weight range
        Wb = tf.dtypes.cast(tf.where(Wb > 0, H, -H), tf.float32)
        return Wb